#!/usr/bin/env bash
# This bash script displays To infinity and beyond indefinitely
# and I am invincible!!! when it catches  SIGTERM signal.

while 'true' 
do
  echo "To infinity and beyond"
  sleep 2
  trap 'echo "I am invincible!!!"' SIGTERM
done
